const UPDATE_PIZZA = "UPDATE_PIZZA";
const UPDATE_PIZZA_SAUSE = "UPDATE_PIZZA_SAUSE";
const UPDATE_PIZZA_SUBINGRIDIENT = "UPDATE_PIZZA_SUBINGRIDIENT";
const RESET_PIZZA = "RESET_PIZZA";
const ADD_PIZZA_TO_CART = "ADD_PIZZA_TO_CART";
const RESET_CART = "RESET_CART";
const UPDATE_PIZZA_CART_COUNTER = "UPDATE_PIZZA_CART_COUNTER";
const EDIT_PIZZA_FROM_CART = "EDIT_PIZZA_FROM_CART";
const UPDATE_PIZZA_AT_CART = "UPDATE_PIZZA_AT_CART";
const SET_CART_MISC = "SET_CART_MISC";
const UPDATE_CART_MISC_COUNTER = "UPDATE_CART_MISC_COUNTER";
const UPDATE_CART_FORM = "UPDATE_CART_FORM";
const UPDATE_CART_POPUP_STATE = "UPDATE_CART_POPUP_STATE";

export {
  UPDATE_PIZZA,
  UPDATE_PIZZA_SAUSE,
  UPDATE_PIZZA_SUBINGRIDIENT,
  RESET_PIZZA,
  ADD_PIZZA_TO_CART,
  RESET_CART,
  UPDATE_PIZZA_CART_COUNTER,
  EDIT_PIZZA_FROM_CART,
  UPDATE_PIZZA_AT_CART,
  SET_CART_MISC,
  UPDATE_CART_MISC_COUNTER,
  UPDATE_CART_FORM,
  UPDATE_CART_POPUP_STATE,
};
